image:
  name: registry.gitlab.com/dtcc-platform/dtcc-builder
  entrypoint: [""]

stages:
  - build
  - test
  - binaries

before_script:
    - echo "Skipping since we are using Gitlab's Docker image registry"

build:
  stage: build
  script:
    #- sudo apt-get install lftp -y # add extra (outside of registered Docker file) dependencies here
    - pwd && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make all && make install
  artifacts:
    paths:
      - bin/
      - build/
      - unittests/

binaries:
  stage: binaries
  script:
    - echo "
      rm -rf temp/;
      mkdir temp/;
      ldd /builds/dtcc-platform/dtcc-builder/bin/dtcc-generate-citymodel |cut -d \" \" -f3|grep .|grep /lib/x86_64-linux-gnu/ -v|
      while IFS= read -r line; do
      echo \"\$line\";
      cp \"\$line\" temp/;
      done;" > myfile.sh
    - chmod +x myfile.sh
    - cat myfile.sh
    - sh ./myfile.sh
    - ls -alt
    - pwd 
  artifacts:
    paths:
      - /builds/dtcc-platform/dtcc-builder/temp/
      - /builds/dtcc-platform/dtcc-builder/bin/dtcc-generate-citymodel
      - /builds/dtcc-platform/dtcc-builder/bin/dtcc-generate-mesh
  needs: [build]

test:
  stage: test
  script:
    - sudo mkdir -p /home/dtcc/dtcc-builder/
    #- cd /builds/
    #- %ls -altR
    - sudo cp -R /builds/dtcc-platform/dtcc-builder/unittests/ /home/dtcc/dtcc-builder/unittests/
    - sudo chmod -R a+rw /home/dtcc/dtcc-builder/unittests/data/*
    - pwd && ls -alt && cd build/ && ./unittests/run-unittests 
  dependencies:
    - build
