image:
  name: registry.gitlab.com/dtcc3d/core
  entrypoint: [""]

stages:
  - build
  - test

before_script:
    - echo "Skipping since we are using Gitlab's Docker image registry"

build:
  stage: build
  script:
    - sudo apt-get install libpng++-dev lftp -y # add extra (outside of registered Docker file) dependencies here
    - pwd && mkdir build && cd build && cmake .. && make all && make install
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - pwd && ls -alt && cd build && ./unittests/run-unittests
  dependencies:
    - build
