image:
  name: registry.gitlab.com/dtcc3d/core
  entrypoint: [""]

stages:
  - build
  - test

before_script:
    - echo "Skipping since we are using Gitlab's Docker image registry"

build:
  stage: build
  script:
    #- sudo apt-get install lftp -y # add extra (outside of registered Docker file) dependencies here
    - pwd && mkdir build && cd build && cmake .. && make all && make install
  artifacts:
    paths:
      - build/
      - unittests/

test:
  stage: test
  script:
    # - pwd && ls -alt && cd unittests/ && ls
    #- pwd && ls -alt && cd ../data && ls -alt && bash dtcc-download-data-unittests
    #- cd unittests/ && wget ftps://cloud.dtcc.chalmers.se/Unittests/Unittests.zip --no-check-certificate && unzip Unittests.zip
    - pwd && ls -alt && cd build/ && ./unittests/run-unittests
  dependencies:
    - build
