version: '3.9'

services:
  dev:
    build: 
      context: ./
      dockerfile: './dtcc-model/docker/Dockerfile'
      target: dev
    container_name: dtccdev
    image: dtcc-platform/dev
    volumes:
      - ./..:/home/dtcc/core
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
