#!/usr/bin/env bash
#
# Simple script for string replacement (for all files in current directory)
# Anders Logg 2020-02-27
#
# Usage: replace <old string> <new string>

OLD=$1
NEW=$2

for f in *; do
    echo "$OLD --> $NEW in $f"
    sed -i "s/$OLD/$NEW/g" $f
done
