version: '3.9'

services:
  builder:
    build:
      context: ../
      dockerfile: './dtcc-model/docker/Dockerfile'
      target: dev
    working_dir: ${WORKING_DIR}
    container_name: dtcc-builder
    image: dtcc-builder-image
    stdin_open: true
    tty: true
    volumes:
      - ../:${WORKING_DIR}
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE


networks:
  default:
    external: true
    name: docker_dtcc-core-network
