#!/usr/bin/env bash
#docker-compose build dev
#docker build -t dtccimage .
docker pull registry.gitlab.com/dtcc3d/core &&
docker tag registry.gitlab.com/dtcc3d/core dtccimage &&
docker rmi -f registry.gitlab.com/dtcc3d/core
