#!/usr/bin/env python3

# VirtualCity@Chalmers: vc-generate-mesh-batch
# Anders Logg 2018]
#
# This script calls vc-generate-mesh to generate meshes for a
# batch of city models. It is assumed that the city models are
# stored as numbered JSON files in the subdirectory CityModels.

import os

# Get list of files
jsonFiles = [f for f in os.listdir('CityModels') if f.endswith('.json')]
jsonFiles.sort()

# Call mesh generator for each frame
for f in jsonFiles:
    p = 'HeightMapGbg.json Parameters.json'
    os.system('./vc-generate-mesh CityModels/%s %s' % (f, p))

# PVD file template
template = """\
<?xml version="1.0"?>
<VTKFile type="Collection" version="0.1">
  <Collection>
%s
  </Collection>
</VTKFile>
"""
line = '    <DataSet timestep="%d" part="0" file="%s"/>'

# Write a top-level PVD file for viewing animation in Paraview
ps = [f.split('.')[0] for f in jsonFiles]
lines = [line % (i, p + 'Mesh000000.vtu') for (i, p) in enumerate(ps)]
with open('CityModels/Mesh.pvd', 'w') as f:
    f.write(template % '\n'.join(lines))
lines = [line % (i, p + 'Boundary000000.vtu') for (i, p) in enumerate(ps)]
with open('CityModels/Boundary.pvd', 'w') as f:
    f.write(template % '\n'.join(lines))
