#!/usr/bin/env python3

# Plot mesh and intermediate mesh data for debugging.
# Copyright (C) 2018 Anders Logg.

import numpy
import pylab
from matplotlib import collections as mc

def ReadCSV(FileName):
    return pylab.genfromtxt(FileName, delimiter=',')

def PlotConvexHull():
    Points = ReadCSV('ConvexHull.csv')
    x = [p[0] for p in Points]
    y = [p[1] for p in Points]
    x = x + [x[0]]
    y = y + [y[1]]
    pylab.figure()
    pylab.plot(x, y, '-o')
    pylab.title('Convex hull (%d points)' % len(Points))

def PlotMesh2D():
    Points = ReadCSV('Mesh2DPoints.csv')
    Cells = ReadCSV('Mesh2DCells.csv').astype('int')
    lines = []
    for t in Cells:
        lines.append((Points[t[0]], Points[t[1]]))
        lines.append((Points[t[1]], Points[t[2]]))
        lines.append((Points[t[2]], Points[t[0]]))
    lc = mc.LineCollection(lines)
    fig, ax = pylab.subplots()
    ax.add_collection(lc)
    ax.autoscale()
    ax.margins(0.1)
    pylab.axis('equal')
    pylab.title('2D mesh (%d cell)' % len(Cells))

def PlotMesh3D():
    print("3D Python plotting not supported; use Paraview.")

PlotMesh2D()
PlotMesh3D()

pylab.show()
