#!/usr/bin/python3
#
# Postprocessing script for dtcc-bench-run

import json, glob
from pylab import *

# Get cases
cases = [f.split('.log')[0] for f in glob.glob('bench-case-*')]

# Get cells
cells = [float(open('%s/bench.log' % c).read().split('3D tetrahedral')[1].split()[5]) for c in cases]

# Sort cases and cells by number of cells
cells, cases = zip(*sorted(zip(cells, cases)))

# Get variables (by looking at the first case)
variables = sorted([k for k in json.load(open('%s/Timings.json' % cases[0])).keys() if 'Step ' in k])

# Get timings
timings = {}
for variable in variables:
    timings[variable] = [json.load(open('%s/Timings.json' % c))[variable]['Mean'] for c in cases]

# Plot timings
for variable in variables:
    loglog(cells, timings[variable], '-o', label=variable)
xlabel('Number of cells')
ylabel('CPU time')
legend()
grid(True)
show()
