#!/usr/bin/env python3

# Simple script for plotting JSON height maps.
# Copyright (C) 2019 Anders Logg.

import sys, numpy, json, pylab

def PlotHeightMap(fileName, plotCountour=False):

    # Read JSON file
    with open(fileName) as f:
        heightMap = json.load(f)

    # Get data
    gridData = heightMap['GridData']
    xMin = heightMap['XMin']
    yMin = heightMap['YMin']
    xMax = heightMap['XMax']
    yMax = heightMap['YMax']
    xSize = heightMap['XSize']
    ySize = heightMap['YSize']

    # Test data for verifying orientation, bump in lower left corner
    # for i in range(len(gridData)):
    #     x = i % xSize
    #     y = i // ySize;
    #     x = float(x) / (xSize - 1)
    #     y = float(y) / (ySize - 1)
    #     gridData[i] = x*(1 - x)**2*y*(1 - y)**2

    # Reshape to 2D grid
    z = numpy.reshape(gridData, (xSize, ySize))

    # Select plot
    if plotContour:
        pylab.contour(z, extent=[xMin, xMax, yMin, yMax])
        pylab.axis('scaled')
        pylab.axis('off')
    else:
        pylab.imshow(z, extent=[xMin, xMax, yMin, yMax], origin='lower')
        pylab.axis('off')

    # Set title
    pylab.title('[%g, %g] x [%g, %g]' % \
                (xMin, xMax, yMin, yMax))

def Help():
    print("Usage: vc-plot-heightmap HeightMap.json contour=1")

if __name__ == "__main__":

    # Check command-line arguments
    if len(sys.argv) < 2:
        Help()
        sys.exit(1)

    # Get arguments
    fileName = sys.argv[1]
    plotContour = len(sys.argv) == 3 and sys.argv[2] == 'contour=1'

    # Plot height map
    PlotHeightMap(fileName, plotContour)
    pylab.show()
