#!/usr/bin/env python3

# Simple script for plotting JSON height maps.
# Copyright (C) 2019 Anders Logg.

import sys, numpy, json, pylab

def PlotHeightMap(fileName):

    # Read JSON file
    with open(fileName) as f:
        heightMap = json.load(f)

    # Get data
    gridData = heightMap['GridData']
    xMin = heightMap['XMin']
    yMin = heightMap['YMin']
    xMax = heightMap['XMax']
    yMax = heightMap['YMax']
    xSize = heightMap['XSize']
    ySize = heightMap['YSize']

    # Test data for verifying orientation
    # for i in range(len(gridData)):
    #     x = i % xSize
    #     y = i // ySize;
    #     gridData[i] = x*y

    # Reshape to 2D grid
    z = numpy.reshape(gridData, (xSize, ySize))

    # Plot heightmap
    pylab.subplot(1, 2, 1)
    pylab.imshow(z, extent=[xMin, xMax, yMin, yMax], origin='lower')
    pylab.title('Height map')

    # Plot contour
    pylab.subplot(1, 2, 2)
    pylab.contour(z, extent=[xMin, xMax, yMin, yMax])
    pylab.axis('scaled')
    pylab.grid(True)
    pylab.title('Contour')

def Help():
    print("Usage: vc-plot-mesh HeightMap.json")

if __name__ == "__main__":

    # Check command-line arguments
    if len(sys.argv) != 2:
        Help()
        sys.exit(1)

    # Get filename
    fileName = sys.argv[1]

    # Plot height map
    PlotHeightMap(fileName)
    pylab.show()
