#!/usr/bin/env bash

echo "Downloading public demo data from data.dtcc.chalmers.se..."
wget http://data.dtcc.chalmers.se:5001/demo-data-public -v -O demo-data-public.tar.gz
tar zxfv demo-data-public.tar.gz
