#!/bin/bash
#read -p "Enter FTP username : " username
#read -s -p "Enter FTP password : " password
while [ -z "$username" ]
do
read -p "Enter FTP username : " username
done
while [ -z "$password" ]
do
read -s -p "Enter FTP password : " password
done
echo "Trying to login to cloud.dtcc.chalmers.se FTP over TLS with username $username ..."
lftp -e "set ssl:verify-certificate no;set ftp:ssl-allow true;set ftp:ssl-protect-data true;mirror --verbose --use-pget-n=8 -c --verbose /Data/ .;" -u $username\,$password ftps://cloud.dtcc.chalmers.se
