#!/usr/bin/env bash

DATATMP=data-repository-tmp

download_ssh()
{
    rm -rf $DATATMP
    git clone git@gitlab.com:dtcc3d/data.git $DATATMP
}

download_https()
{
    rm -rf $DATATMP
    git clone https://gitlab.com/dtcc3d/data.git $DATATMP
}

# Select download: SSH or HTTPS
echo "Connecting..."
while true; do
    read -p "Download data via SSH (or otherwise use HTTPS)? [y/n] " YN
    case $YN in
        [Yy]* ) download_ssh break;;
        [Nn]* ) download_https break;;
        * ) echo "Please answer yes or no.";;
    esac
    break
done

# Clean up
echo "Pulling LFS"
git -C $DATATMP/ lfs pull
echo "Moving and cleaning up..."
rsync --info=progress2 -a $DATATMP/ .
#cp -r $DATATMP/* . &&
rm -rf $DATATMP README.md
echo "Download complete"
