#!/usr/bin/env bash
# Check info (bounds) for all LAS files in current directory
# Anders Logg 2021-10-22

LOGFILE="lasinfo.log"

rm -f $LOGFILE

for f in *.las; do
    echo "--------------------------------------------------------------------------------------------------------" | tee -a $LOGFILE
    echo "Filename: $f" | tee -a $LOGFILE
    dtcc-info $f | tee -a $LOGFILE
done

echo ""
echo "Log written to $LOGFILE"
