#!/usr/bin/env bash

docker pull registry.gitlab.com/dtcc-platform/dtcc-builder &&
docker tag registry.gitlab.com/dtcc-platform/dtcc-builder dtccimage &&
docker rmi -f registry.gitlab.com/dtcc-platform/dtcc-builder
