#!/usr/bin/env bash
#
# Demo of the mesh generation pipeline
for j in Kungsholmen Hammarkullen Johanneberg Kungsholmen Orebro
do
PARAMETERS=$j.json
#PARAMETERS=Hammarkullen.json
#PARAMETERS=Johanneberg.json
#PARAMETERS=Kungsholmen.json
#PARAMETERS=Orebro.json
#PARAMETERS=Test.json

dir=`echo $PARAMETERS|cut -d "." -f1`
echo $dir
mkdir -p $dir

for i in generate-elevation-model generate-citymodel generate-visualization-mesh generate-visualization-mesh generate-visualization-mesh smooth-ground-mesh
do
echo "Running dtcc-$i..."
../bin/dtcc-$i $PARAMETERS
done
done
