#!/usr/bin/env bash
#
# Demo of pipeline for simulation mesh generation. Requires JSON filename as argc 1.

# Exit on errors
set -e

# Generate elevation model
../bin/dtcc-generate-elevation-model $1 > $1\.log &&
sleep 3

# Generate city model
../bin/dtcc-generate-citymodel $1 >> $1\.log &&
sleep 3

# Generate simulation mesh
../bin/dtcc-generate-simulation-mesh $1  >> $1\.log
