#!/usr/bin/env bash
#
# Demo of pipeline for visualization mesh generation.

PARAMETERS=Hammarkullen.json

# Exit on errors
set -e

# Generate elevation model
../bin/dtcc-generate-elevation-model $PARAMETERS

# Generate city model
../bin/dtcc-generate-citymodel $PARAMETERS

# Generate visualization mesh
../bin/dtcc-generate-visualization-mesh $PARAMETERS

# Smooth ground mesh
../bin/dtcc-smooth-ground-mesh $PARAMETERS
