#!/usr/bin/env bash
#
# Demo of the mesh generation pipeline

PARAMETERS=Hammarkullen.json
#PARAMETERS=Johanneberg.json
#PARAMETERS=Orebro.json
#PARAMETERS=Kungsholmen.json
#PARAMETERS=Test.json

# Exit on errors
set -e

# Generate height map
../bin/dtcc-generate-heightmap $PARAMETERS

# Generate city model
../bin/dtcc-generate-citymodel $PARAMETERS

# Generate visualization mesh
../bin/dtcc-generate-visualization-mesh $PARAMETERS

# Generate simulation mesh
../bin/dtcc-generate-simulation-mesh $PARAMETERS

# Smooth ground mesh
../bin/dtcc-smooth-ground-mesh $PARAMETERS
