#!/usr/bin/env bash
#
# Demo of the mesh generation pipeline

PARAMETERS=Hammarkullen.json
#PARAMETERS=Johanneberg.json
#PARAMETERS=Orebro.json
#PARAMETERS=Kungsholmen.json
#PARAMETERS=Test.json

# Exit on errors
set -e

# Generate elevation model
#../bin/dtcc-generate-elevation-model $PARAMETERS

# Generate city model
#../bin/dtcc-generate-citymodel $PARAMETERS

# Generate visualization mesh
#../bin/dtcc-generate-visualization-mesh $PARAMETERS

# Generate simulation mesh
../bin/dtcc-generate-simulation-mesh $PARAMETERS

# Smooth ground mesh
#../bin/dtcc-smooth-ground-mesh $PARAMETERS
