#!/usr/bin/env bash

# List of available datasets
DATASETS=(HelsingborgResidential2022 "Urban area in Helsingborg, Sweden"
          HelsingborgHarbour2022     "Harbour area in Helsingborg, Sweden"
          SimulationDemo2023         "Urban area used for simulation demo")

# Select dataset
DATASET=$(dialog --clear \
          --backtitle "DTCC Builder Demo" \
          --menu "Please select a dataset" 0 0 0 "${DATASETS[@]}" \
          2>&1 >/dev/tty)
clear

# Check if dataset exists
#DATA_DIRECTORY="../data/$DATASET"
#if [ ! -f "$DATA_DIRECTORY/PropertyMap.shp" ]; then
#    echo "*** Dataset $DATASET not found"
#    echo "*** Make sure to run ./dtcc-download-demo-data-public in the data directory"
#    exit 1
#fi

echo "Running demo for data set $DATASET..."

# Run city model generation
../bin/dtcc-generate-citymodel $DATASET.json

# Adjust city model for simulation demo (to make it more interesting)
if [ "$DATASET" == "SimulationDemo2023" ]; then
    python3 adjust_simulation_citymodel.py 
fi

# Run city model generation
../bin/dtcc-generate-mesh $DATASET.json

echo ""
echo "Demo completed."
