#!/bin/bash
#
# Runner for demo run of parameters in parallel. Tread carefull in terms of RAM!

PARAMETERS=test
name=ElevationModelResolution
for i in 0.5 1 2 4 #8 16 32
do
value=$i
jq --argjson key1  "$value" --arg name "$name" '.[$name] = $key1' Majorna2021.json|sponge $PARAMETERS\_$i\.json
# Generate elevation model
#(time ./dtcc-demo-pipeline-1arg $PARAMETERS\_$i\.json ) &
#sleep 2
done
