#!/usr/bin/env bash
#
# Demo of pipeline for simulation mesh generation.

PARAMETERS=Hammarkullen2020.json

# Exit on errors
set -e

# Generate city model
#../bin/dtcc-generate-citymodel $PARAMETERS

# Generate simulation mesh
../bin/dtcc-generate-simulation-mesh $PARAMETERS
