#!/usr/bin/env bash
#
# Demo of the mesh generation pipeline, including
#
# 1. Height map generation:  vc-generate-heightmap
# 2. City model generation:  vc-generate-citymodel
# 3. Volume mesh generation: vc-generate-mesh

# Generate height map
../bin/vc-generate-heightmap Parameters.json

# Generate city model
../bin/vc-generate-citymodel Parameters.json

# Generate mesh
../bin/vc-generate-mesh Parameters.json
