name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BRANCH: develop

jobs:
  build:

    runs-on: ubuntu-22.04 #self-hosted
    # Placeholder for Docker on our Amazon AWS Runner
    #container:
    #  image: ubuntu-latest
    #  options: --user 1000


    steps:
    # VN at 16 March 2023: checkout/v3 causes some weird issues, so went for manual cloning instead...
    #- uses: actions/checkout@v3
    - name: clone repo
      run: sudo apt-get install libtriangle-dev libgeos-dev && git clone https://github.com/dtcc-platform/${{ github.event.repository.name }} -b $BRANCH && pwd
    - name: pip install
      run: export "DEB_PYTHON_INSTALL_LAYOUT=deb_system" && pip install ${{ github.event.repository.name }}/
    #- name: cmake install
    #  run: cd ${{ github.event.repository.name }}/build/ && cmake .. && make all && sudo make install && cd ..
    - name: run tests
      run: cd ${{ github.event.repository.name }}/tests && pwd && ls -alt && sh run-tests
    - name : dispatch
      if: always()
      run: |
           curl -L -X POST \
           -H "Accept:application/vnd.github+json" \
           -H "Authorization:token ${{ secrets.TOKEN }}" \
           -H "X-GitHub-Api-Version:2022-11-28" \
           https://api.github.com/repos/dtcc-platform/dtcc-docs/actions/workflows/manual.yml/dispatches \
           -d '{"ref":"develop","inputs":{"name":"Me"}}'
    - name: cleanup op
      if: always()
      run : sudo find /Runner/Runner/_work/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
    - name: report failure
      if: failure()
      #with:
      # status: ${{ job.status }}
      # notify_when: 'failure'
      run: |
            curl -L -X POST $SLACK_URL -d "payload={\"channel\": \"#development\", \"username\": \"Github Runner\", \"text\": \"CI has been broken! Repo: ${{ github.event.repository.name }}. Commit message: ${{ github.event.head_commit.message }}. Author: ${{ github.event.commits[0].author.name}}
            \", \"icon_emoji\": \":ghost:\"}"
      env:
       SLACK_URL: ${{ secrets.SLACK_URL }}    
        # This fails after checkout/v3 was not used
    #- name: more cleanup ops
    #  run : pwd && sudo rm -rf /home/ubuntu/Runner/actions-runner/_work/${{ github.event.repository.name }}
    
